language: go

go:
  - "1.x"
  - tip

install:
  - go get github.com/stretchr/testify/assert
  - go get golang.org/x/text/encoding/charmap
  - go get -v github.com/axw/gocov/gocov
  - go get -v github.com/mattn/goveralls
script:
  - $HOME/gopath/bin/goveralls -service=travis-ci