name: Create Release

on:
  push:
    tags: [ "v*.*.*" ]
  pull_request:
    branches: [ master ]

jobs:
  testing:
    name: Testing
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Check
      run: make check

  create_release:
      runs-on: ubuntu-latest
      steps:
        -
          name: Checkout
          uses: actions/checkout@v2
          with:
            fetch-depth: 0
        -
          name: Set up Go
          uses: actions/setup-go@v2
          with:
            go-version: 1.16
        -
          name: Run GoReleaser
          uses: goreleaser/goreleaser-action@v2
          with:
            # either 'goreleaser' (default) or 'goreleaser-pro'
            distribution: goreleaser
            version: latest
            args: release --rm-dist
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker:
    name: Docker
    needs: [testing, create_release]
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Docker
      run: make docker

    - name: Docker Push
      run: |+
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          make release-push
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
